---
name: Release
on:
  push:
    tags:
      - '*'
permissions :
  contents: write
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: gcc puissance.c -o puissance-windows.exe
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: puissance-windows
          path: ./puissance-windows.exe

  build-macos:
      runs-on: macos-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Build
          run: gcc puissance.c -o puissance-macos
        - name: Upload
          uses: actions/upload-artifact@master
          with:
            name: puissance-macos
            path: ./puissance-macos

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: gcc puissance.c -o puissance-linux.bin
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: puissance-ubuntu
          path: ./puissance-linux.bin

  download-exec_release:
    needs: [build-windows,build-macos,build-ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Download puissance-windows artifact
        uses: actions/download-artifact@master
        with:
          name: puissance-windows
          path: ./artifacts
      - name: Download puissance-macos artifact
        uses: actions/download-artifact@master
        with:
          name: puissance-macos
          path: ./artifacts
      - name: Download puissance-ubuntu artifact
        uses: actions/download-artifact@master
        with:
          name: puissance-ubuntu
          path: ./artifacts
      - name: checkoutRepository
        uses: actions/checkout@v4
      - name: release Creation
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            /home/runner/work/testPHP/testPHP/artifacts/puissance-windows.exe
            /home/runner/work/testPHP/testPHP/artifacts/puissance-macos
            /home/runner/work/testPHP/testPHP/artifacts/puissance-ubuntu.bin